---
- name: Check if app folders exist
  stat:
    path: "{{ base_path }}/{{ item }}"
  loop: "{{ app_folders }}"
  loop_control:
    label: "{{ item }}"
  register: folder_check

- name: Run docker compose up -d in each app folder
  command: docker compose up -d
  args:
    chdir: "{{ base_path }}/{{ item.item }}"
  when: item.stat.exists
  loop: "{{ folder_check.results }}"
  loop_control:
    label: "{{ item.item }}"

- name: Warn if any folders were missing
  debug:
    msg: "Folder '{{ item.item }}' does not exist. Skipping."
  when: not item.stat.exists
  loop: "{{ folder_check.results }}"
  loop_control:
    label: "{{ item.item }}"
