---
- name: Deploy multiple Docker Compose apps
  block:
    - name: Check if {{ item }} folder exists
      stat:
        path: "{{ base_path }}/{{ item }}"
      register: folder_check
      loop: "{{ app_folders }}"
      loop_control:
        label: "{{ item }}"
    
    - name: Debug the folder_check result
      debug:
        msg: "Folder check result for {{ item }}: {{ folder_check.results }}"

    - name: Run docker-compose up -d in each app folder
      command: docker-compose up -d
      args:
        chdir: "{{ base_path }}/{{ item.item }}"
      when: item.stat.exists
      loop: "{{ folder_check.results }}"
      loop_control:
        label: "{{ item.item }}"

    - name: Warn if any folders were missing
      debug:
        msg: "Folder '{{ item.item }}' does not exist. Skipping."
      when: not item.stat.exists
      loop: "{{ folder_check.results }}"
      loop_control:
        label: "{{ item.item }}"
